# Generated by Django 4.1.3 on 2022-11-21 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0005_alter_property_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insan', to=settings.AUTH_USER_MODEL),
        ),
    ]
